@base=http://127.0.0.1:3333

### create
POST {{base}}/clip
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzA5ZjBkNWM1YzlkZDAyMThlNDE0NCIsInRpbWVzdGFtcCI6IjIwMjAtMTEtMjdUMTk6Mzg6MjQuNjU2ODE3KzA4OjAwIn0.VsDhIncfIVNUbkWgrEjPwEbVSQNAOOEUgWtR7eWujWw
Accept-Language: en

{
  "type": 1,
  "content": "sss"
}

### query
GET {{base}}/clip/5fc104d007b3bbe249d7d9bb
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzA5ZjBkNWM1YzlkZDAyMThlNDE0NCIsInRpbWVzdGFtcCI6IjIwMjAtMTEtMjdUMTk6Mzg6MjQuNjU2ODE3KzA4OjAwIn0.VsDhIncfIVNUbkWgrEjPwEbVSQNAOOEUgWtR7eWujWw

### get
GET  {{base}}/clip?page=2&size=3000
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzA5ZjBkNWM1YzlkZDAyMThlNDE0NCIsInRpbWVzdGFtcCI6IjIwMjAtMTEtMjdUMTk6Mzg6MjQuNjU2ODE3KzA4OjAwIn0.VsDhIncfIVNUbkWgrEjPwEbVSQNAOOEUgWtR7eWujWw

### register
POST  {{base}}/auth/register
Content-Type: application/json

{
  "username": "test",
  "password": "test",
  "email": "2@q.com"
}

### login
POST {{base}}/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}
